"""add_column_puroduct_number_tb

Revision ID: bdd19fa63016
Revises: 
Create Date: 2025-06-24 11:25:25.839958

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bdd19fa63016'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product_number', schema=None) as batch_op:
        batch_op.add_column(sa.Column('serial_no', sa.String(length=20), nullable=False,server_default=''))
        batch_op.add_column(sa.Column('material', sa.String(length=20), nullable=False,server_default=''))
        batch_op.add_column(sa.Column('material_thickness', sa.Float(), nullable=False,server_default=''))
        batch_op.add_column(sa.Column('cut_length', sa.Float(), nullable=False,server_default=''))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product_number', schema=None) as batch_op:
        batch_op.drop_column('cut_length')
        batch_op.drop_column('material_thickness')
        batch_op.drop_column('material')
        batch_op.drop_column('serial_no')

    # ### end Alembic commands ###
